DBHOST: localhost
DBNAME: chatTest
DBUSERNAME: local
DBPASSWORD: toor
PORT: 9999
DBCONNPARAMS: "sslmode=disable"
DBPROTOCOL: "postgresql"
SESSIONSECRETKET: "JEq6UyiiAGG75EXuROP48KUdPMC6k"
AWSACCESSKEYID: "AHU59XGVJIPUPRPZVGQK"
AWSSECRETACCESSKEY: "17Nf+elmod/JEq6UyiiAGG75EXuROP48KUdPMC6k"
AWSBUCKET: "palomino-local"
AWSENDPOINTURL: "http://localhost:9001"
AWSREGION: "us-east-4"
CSRFSECRETKEY: "JEq6UPUPRlmodost"
CSRFSECURE: false
REDISHOST: "localhost:6379"
REDISPASSWORD: ""
REDISDB: 0
